version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: rate_limiter_redis
    ports:
      - "6379:6379"
    restart: always

  app:
    build:
      context: .
    container_name: rate_limiter_app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env
    restart: on-failure
